AWSTemplateFormatVersion : '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31
  
Parameters:
  BucketName: 
    Type: String
    
Description: my template
Resources:
    MyLambda1:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: lambdaCloudFormationLab2
            Runtime: python3.6
            CodeUri: ./build
            Handler: my_lambda.handler
            Role: !GetAtt MyLambdaRole.Arn

